name: asdf
channels:
  - conda-forge
dependencies:
  - python=3.10
  - boto3
  - astropy
  - clize
  - cytoolz
  - fast-histogram
  - fs
  - gspread
  - ipython
  - jupyter
  - matplotlib
  - more-itertools
  - multidict
  - numpy
  - opencv
  - pandas
  - pathos
  - pds4_tools
  - pillow
  - pip
  - pydrive2
  - pytest
  - python-dateutil
  - python-Levenshtein
  - rich
  - scipy
  - sympy
