name: asdf
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - dustgoggles
  - pandas
  - matplotlib
  - git
  - jupyter
  - pdr
  - clize
  - ipython
  - pvl
  - python-Levenshtein
  - scipy
  - opencv
  - fs
  - gspread
  - boto3
  - pathos
  - rich
  - astropy
  - sympy
  - pytest
  - pydrive2
  - marslab
