name: asdf
channels:
  # note: packages _must_ be installed from conda-forge. defaults has a newer/incompatible version of libgsl.
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - dustgoggles
  - pandas
  - matplotlib
  - git
  - jupyter
  - pdr
  - clize
  - ipython
  - python-Levenshtein
  - scipy
  - opencv
  - fs
  - gspread
  - boto3
  - pathos
  - rich
  - astropy
  - sympy
  - pytest
  - pydrive2
  - marslab
  - hugin
  - scikit-image
  - sh
  - pip
  - pip:
      - git+https://github.com/MillionConcepts/pretty-plot.git
