from pathlib import Path


MARSLAB_VARCOLS = ("CREATOR", "FILE_TIMESTAMP", ".*_PATH$", "ASDF_VERSION")
"""
Regex patterns for marslab file columns we expect to differ between asdf runs.
"""

NAVEVAL_VARCOLS = (".*_fn",)
"""
Regex patterns for naveval file columns we expect to differ between asdf 
runs.
"""

SPACE_VARKEYS = ("ZDITHER0",)
"""
Regex patterns for spatial FITS header keywords we expect to differ between
asdf runs. 
"""

ALWAYS_SKIP_FILES = (r"\.DS_Store",)
"""
File patterns we should always skip because they are autogenerated by the OS, 
not asdf
"""

# system paths for various sorts of test files
E2E_FAILURE_DIR = Path(__file__).parent.parent / "e2e_failure_dumps"
TEST_OUTPUT_DIR = Path(__file__).parent.parent / "temp/test_outputs"
REGEN_OUTPUT_DIR = Path(__file__).parent.parent / "temp/regen_outputs"
REF_INPUT_DIR = Path(__file__).parent.parent / "data/reference_inputs"
REF_OUTPUT_DIR = Path(__file__).parent.parent / "data/reference_outputs"
